import java.awt.Desktop.Action;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JLabel;
/*/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JTextField;

/**
 *
 * @author Ahmed and Rodrigo
 */
public class FinalProjectCalculatorTester extends javax.swing.JFrame {
    private double a = 0; // To store the first number  
    private double b = 0; // To store the second number
    private String operator = ""; // To store the operator
    private boolean isNewInput = true; // shows if the input is a new number
    private StringBuilder equation = new StringBuilder(); // For the jlabel
    
   
    
    /**
     * Creates new form Calculator
     */
    public FinalProjectCalculatorTester() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        sqrtButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        expButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        subtractButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();
        dotButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       
        // Type the number first, then press the sqrt button. 
        sqrtButton.setText("√");
        sqrtButton.addActionListener(new java.awt.event.ActionListener() 
        {
            public void actionPerformed(java.awt.event.ActionEvent evt) 
            {
                jButton1ActionPerformed(evt);
                if (isNewInput) 
                {
                    try {
                        // Get the number from the text field and parse it to double
                        a = Double.parseDouble(jTextField1.getText());
                        operator = "sqrt"; // Set the operator for square root
                        jTextField1.setText(""); // Clear the text field for the next input
                        isNewInput = false; // no longer entering a new input
                    } catch (NumberFormatException e) 
                    {
                        // Handles invalid number input
                        jTextField1.setText("Error, invalid input");
                    }
                }

            }
        });

        sevenButton.setText("7");
        sevenButton.addActionListener(new ActionListener() 
        {
            public void actionPerformed(ActionEvent ae)
            {
                jTextField1.setText(jTextField1.getText() + "7");
               
                jLabel1.setText(equation.toString());
            }
        });
        

        fourButton.setText("4");
        fourButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae)
            {
                jTextField1.setText(jTextField1.getText() + "4");
                
                jLabel1.setText(equation.toString());
                
            }
        });
        
            
       

        oneButton.setText("1");
        oneButton.addActionListener(new ActionListener() 
        {
            public void actionPerformed(ActionEvent ae)
            {
                jTextField1.setText(jTextField1.getText() + "1");
                jLabel1.setText(equation.toString());

            }
        });

        expButton.setText("^");
        expButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
             {
                a = Double.parseDouble(jTextField1.getText()); // Store the first number
                operator = "^"; // Store the operator
                jTextField1.setText(""); // Clear the text field for the next input

             }
        });
         
        //Type the number first, then press the log button. 
        logButton.setText("log");
        logButton.addActionListener(new java.awt.event.ActionListener() 
        {

            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                
                jButton6ActionPerformed(evt);
                try {
                    a = Double.parseDouble(jTextField1.getText()); // Get the input number
                    operator = "log"; 
                    //System.out.println("Log at  a = " + a); // Debugging info
                    jTextField1.setText(""); // Clear text field for clarity
                } catch (NumberFormatException e) 
                {
                    jTextField1.setText("Error: Invalid Input"); // Handles invalid input gracefully
                }
                
            }
        });

        eightButton.setText("8");
        eightButton.addActionListener(new ActionListener() 
        {
            public void actionPerformed(ActionEvent ae)
            {
                jTextField1.setText(jTextField1.getText() + "8");
                jLabel1.setText(equation.toString());

            }
        });
        

        fiveButton.setText("5");
        fiveButton.addActionListener(new java.awt.event.ActionListener() 
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
             {
                jButton8ActionPerformed(evt);
                jTextField1.setText(jTextField1.getText() + "5");
                jLabel1.setText(equation.toString());
            }
        });

        nineButton.setText("9");
        nineButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae)
            {
                jTextField1.setText(jTextField1.getText() + "9");
                jLabel1.setText(equation.toString());

            }
        });

        sixButton.setText("6");
        sixButton.addActionListener(new java.awt.event.ActionListener() 
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
             {
                jButton10ActionPerformed(evt);
               jTextField1.setText(jTextField1.getText() + "6");
               jLabel1.setText(equation.toString());
            }
        });

        twoButton.setText("2");
        twoButton.addActionListener(new ActionListener() 
        {
            public void actionPerformed(ActionEvent ae)
            {
                jTextField1.setText(jTextField1.getText() + "2");
                jLabel1.setText(equation.toString());
       
            }
        });

        threeButton.setText("3");
        threeButton.addActionListener(new ActionListener() 
        {
            public void actionPerformed(ActionEvent ae)
            {
               
                jTextField1.setText(jTextField1.getText() + "3");
                jLabel1.setText(equation.toString());

            }
        });

        zeroButton.setText("0");
        zeroButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae)
            {
               
                jTextField1.setText(jTextField1.getText() + "0");
                jLabel1.setText(equation.toString());

            }
        });

        divideButton.setText("/");
        divideButton.addActionListener(new ActionListener()
         {
            public void actionPerformed(ActionEvent ae)
            {   
                  a = Double.parseDouble(jTextField1.getText()); // Store the first number
                   operator = "/"; // Store the operator
                  
                  jTextField1.setText(""); // Clear the text field for the next input
            }
        });

        multiplyButton.setText("*");
        multiplyButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae)
            { 
                a = Double.parseDouble(jTextField1.getText()); // Store the first number
                operator = "*"; // Set the operator
                
                 jTextField1.setText(""); // Clear the text field for the second number
             }
            
        });

        subtractButton.setText("-");
        subtractButton.addActionListener(new ActionListener()
         {
            public void actionPerformed(ActionEvent ae)
            {
                a = Double.parseDouble(jTextField1.getText()); // Store the first number
                operator = "-"; // Store the operator
               
                jTextField1.setText(""); // Clear the text field for the next input
            }
        });

        addButton.setText("+");
       addButton.addActionListener(new ActionListener() 
        {
            public void actionPerformed(ActionEvent ae)
            {
                
                a = Double.parseDouble(jTextField1.getText()); // Store the first number
                operator = "+"; // Store the operator
                equation.append(jTextField1.getText()).append(" + ");
                jLabel1.setText(equation.toString()); 
                jTextField1.setText(""); // Clear the text field for the next input
           
            }
        });

        deleteButton.setText("delete");
        deleteButton.addActionListener(new ActionListener() 
        {
            public void actionPerformed(ActionEvent ae)
            {
               jTextField1.setText("");
                a = 0;
                b = 0;
                operator = "";
                isNewInput = true;

            }
        });
       
         // We added the Operation methods here.
        equalButton.setText("=");
        equalButton.addActionListener(new ActionListener() 
        {
            public void actionPerformed(ActionEvent ae)
            {
                double result = 0;
                switch (operator) 
                {
                    case "+":
                        b = Double.parseDouble(jTextField1.getText());
                        result = Operations.add(a, b);
                        break;
                    case "-":
                        b = Double.parseDouble(jTextField1.getText());
                        result = Operations.subtract(a,b);
                        break;
                    case "*":
                        b = Double.parseDouble(jTextField1.getText());
                        result = Operations.multiply(a, b);
                        break;
                    case "/":
                        b = Double.parseDouble(jTextField1.getText());
                        if (b != 0) 
                        {
                            result = Operations.divide(a, b);
                        } else
                         {
                            jTextField1.setText("Error: Division by Zero");
                            return;
                        }
                        break;
                    case "^":
                        b = Double.parseDouble(jTextField1.getText());
                        result = Operations.power(a, b);
                        break;
                    case "sqrt":
                        result = Operations.squareRoot(a); // Perform square root on `a`
                        break;
                    case "log":
                     if (a > 0) 
                    {
                        result = Math.log10(a); // Use base 10 logarithm
                        result = Math.round(result); // Round to the nearest whole number
                       // System.out.println("Computed log(a): " + result); // Debugging info
                    } else {
                        jTextField1.setText("Error: Invalid Input for Log");
                        return;
                    }
                        break;
                    default:
                        jTextField1.setText("Error: Unknown Operator");
                        return;
                }
        
                jTextField1.setText(String.valueOf(result)); // Display the result
                equation.setLength(0); 
                equation.append(result); // Start new equation with the result
                jLabel1.setText(equation.toString());
                operator = ""; // Reset the operator
                
            
            }
        });

        dotButton.setText(".");
        dotButton.addActionListener(new ActionListener() 
        {
            public void actionPerformed(ActionEvent ae)
            {
                jTextField1.setText(jTextField1.getText() + ".");

            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sevenButton)
                    .addComponent(sqrtButton)
                    .addComponent(fourButton)
                    .addComponent(oneButton)
                    .addComponent(zeroButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fiveButton)
                                .addGap(18, 18, 18)
                                .addComponent(sixButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(twoButton)
                                    .addComponent(dotButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(threeButton)
                                    .addComponent(equalButton))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(addButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(deleteButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(subtractButton)
                                .addGap(9, 9, 9))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(eightButton)
                            .addGap(18, 18, 18)
                            .addComponent(nineButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(multiplyButton))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(expButton)
                            .addGap(17, 17, 17)
                            .addComponent(logButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(divideButton))))
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sqrtButton)
                    .addComponent(expButton)
                    .addComponent(logButton)
                    .addComponent(divideButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sevenButton)
                    .addComponent(eightButton)
                    .addComponent(nineButton)
                    .addComponent(multiplyButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourButton)
                    .addComponent(fiveButton)
                    .addComponent(sixButton)
                    .addComponent(subtractButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twoButton)
                    .addComponent(oneButton)
                    .addComponent(threeButton)
                    .addComponent(addButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zeroButton)
                    .addComponent(deleteButton)
                    .addComponent(equalButton)
                    .addComponent(dotButton))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        


   
  

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalProjectCalculatorTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalProjectCalculatorTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalProjectCalculatorTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalProjectCalculatorTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalProjectCalculatorTester().setVisible(true);
            }
        });
    
      
    
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton sqrtButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton zeroButton;
    private javax.swing.JButton divideButton;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton subtractButton;
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton dotButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton expButton;
    private javax.swing.JButton logButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
